# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, main]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$TUcxb0KhdTL0ndmJXbZeSePmKaC9WPOR4qLiY/0ef.gGQAV5gKs5y
                        roles: 'ROLE_ADMIN'

        main:
            entity:
                class: Cvut\Fit\BiWT1\Blog\BaseBundle\Entity\User
                property: name

        api_key_user_provider:
            id: cvut_fit_bi_wt1_blog_base.security.api_key_user_provider

    encoders:
            Cvut\Fit\BiWT1\Blog\BaseBundle\Entity\User:
                algorithm: bcrypt
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        # dev:
        #main:
        #    anonymous: ~
        dev:
                pattern:    ^/(_profiler|_wdt|css|js)
                security:   false
        api:
                            pattern:   ^/api
                            anonymous: false
                            stateless: true
                            simple_preauth:
                                authenticator: cvut_fit_bi_wt1_blog_base.security.api_key_authenticator
                            provider: api_key_user_provider
        secured_area:
                    pattern:   ^/
                    anonymous: ~
                    provider: chain_provider
                    form_login:
                        login_path: login
                        check_path: login
        # ...
                    logout:
                        path: /logout
                        target: /

    # ...
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post/.*/detail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post, roles: [ROLE_USER, ROLE_ADMIN] }
        #- { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
